# Generated by Django 3.2.6 on 2021-08-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('phonenum', models.IntegerField()),
                ('firstname', models.CharField(max_length=70)),
                ('lastname', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=70)),
                ('re_enter', models.CharField(max_length=70)),
            ],
        ),
    ]
