# Generated by Django 3.2.6 on 2021-08-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsewabackend', '0002_auto_20210824_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
                ('location', models.CharField(max_length=70)),
            ],
        ),
    ]
