# Generated by Django 3.2.6 on 2021-09-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsewabackend', '0002_auto_20210824_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('Choose_restaurant', models.CharField(choices=[('Bajeko sekuwa', 'Bajeko sekuwa'), ('KFC', 'KFC'), ('Pepe Pizza', 'Pepe Pizza'), ('Sinka', 'Sinka'), ('Trisara', 'Trisara')], default='Bajeko sekuwa', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='media/')),
                ('name', models.CharField(max_length=70)),
                ('contact', models.IntegerField()),
                ('location', models.CharField(max_length=70)),
            ],
        ),
    ]
