# Generated by Django 3.2.6 on 2021-08-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsewabackend', '0003_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='photo',
            field=models.FileField(upload_to='media/'),
        ),
    ]
