# Generated by Django 3.2.9 on 2021-12-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsewabackend', '0003_menu_restaurants'),
        ('foodsewabackend', '0005_menu'),
    ]

    operations = [
    ]
